apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: {{ include "mlops.fullname" . }}-deployer-service-account
  namespace: {{ .Release.Namespace }}
secrets:
  - name: {{ include "mlops.fullname" . }}-deployer-service-account-token
