apiVersion: v1
data:
  certificate: {{ .Values.mlops.base64_deployer_tls_server_certificate }}
  key: {{ .Values.mlops.base64_deployer_tls_server_key }}
kind: Secret
metadata:
  name: {{ include "mlops.fullname" . }}-deployer-tls-server
  namespace: {{ .Release.Namespace }}
type: Opaque
