apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlops.fullname" . }}-deployer-environments
  namespace: {{ .Release.Namespace }}
data:
  {{ $val := include "mlops.fullname" . }}
  CONFIG_FORCE_deployer_environments_kubernetes_0_ca__cert__data: "{{ .Values.mlops.base64_deployer_kubernetes_certificate_authority_data }}"
  CONFIG_FORCE_deployer_environments_kubernetes_0_driverless__license__secret: {{ printf "%s-driverless-license" $val | b64enc }}
  CONFIG_FORCE_deployer_environments_kubernetes_0_fetcher__secrets_ca: {{ printf "%s-ca" $val | b64enc}}
  CONFIG_FORCE_deployer_environments_kubernetes_0_fetcher__secrets_cert: {{ printf "%s-fetcher-tls-client" $val | b64enc }}
  CONFIG_FORCE_deployer_environments_kubernetes_0_fetcher__secrets_key: {{ printf "%s-fetcher-tls-client" $val | b64enc }}
  CONFIG_FORCE_deployer_environments_kubernetes_0_name: {{ printf "kubernetes" | b64enc }}
  CONFIG_FORCE_deployer_environments_kubernetes_0_namespace: {{ printf "keycloak" | b64enc}}
  CONFIG_FORCE_deployer_environments_kubernetes_0_token: {{ .Values.mlops.deployer_kubernetes_token | b64enc }}
type: Opaque
