apiVersion: v1
data:
  ca.crt: {{ .Values.mlops.base64_deployer_kubernetes_certificate_authority_data }}
  namespace: {{ include "mlops.deployerNamespace" . | b64enc }}
  token: {{ .Values.mlops.deployer_kubernetes_token | b64enc }}
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ include "mlops.fullname" . }}-deployer-service-account
  name: {{ include "mlops.fullname" . }}-deployer-service-account-token
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/service-account-token
