apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops.fullname" . }}-deployer
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 9980
      protocol: TCP
      targetPort: 9980
  selector:
    app: {{ include "mlops.fullname" . }}-deployer
  type: {{ .Values.mlops.service_type }}
