apiVersion: v1
data:
  certificate: {{ .Values.mlops.base64_driverless_tls_client_certificate }}
  key: {{ .Values.mlops.base64_driverless_tls_client_key}}
kind: Secret
metadata:
  name: {{ include "mlops.fullname" . }}-driverless-tls-client
  namespace: {{ .Release.Namespace }}
type: Opaque
