apiVersion: v1
data:
  license.sig: {{ .Values.mlops.base64_driverless_license_key }}
kind: Secret
metadata:
  name: {{ include "mlops.fullname" . }}-driverless-license
  namespace: {{ .Release.Namespace }}
type: Opaque
