apiVersion: v1
data:
  certificate: {{ .Values.mlops.base64_fetcher_tls_client_certificate }}
  key: {{ .Values.mlops.base64_fetcher_tls_client_key }}
kind: Secret
metadata:
  name: {{ include "mlops.fullname" . }}-fetcher-tls-client
  namespace: {{ .Release.Namespace }}
type: Opaque
