apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 9500
      protocol: TCP
      targetPort: 9500
  selector:
    app: {{ include "mlops.fullname" . }}-gateway
  type: {{ .Values.mlops.service_type }}
