apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mlops.fullname" . }}-grafana-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mlops.grafana_data_volume_size }}
  storageClassName: {{ .Values.mlops.storage_class_name }}
