apiVersion: v1
data:
  user: {{ "admin" | b64enc }}
  password: {{ "admin" | b64enc }}
kind: Secret
metadata:
  name: {{ include "mlops.fullname" . }}-grafana-admin
  namespace: {{ .Release.Namespace }}
type: Opaque
