apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "mlops.labels" . | nindent 4 }}
  name: {{ include "mlops.fullname" . }}-ingestion
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "mlops.fullname" . }}-ingestion
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "mlops.fullname" . }}-ingestion
      namespace: {{ .Release.Namespace }}
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: {{ include "mlops.fullname" . }}-ingestion-env
                optional: false
          image: {{ .Values.mlops.model_ingestion_image }}
          imagePullPolicy: {{ .Values.mlops.image_pull_policy }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9911
            timeoutSeconds: 1
          name: {{ include "mlops.fullname" . }}-ingestion
          ports:
            - containerPort: 9911
              protocol: TCP
          volumeMounts:
            - mountPath: /pki/ca
              name: tls-ca
            - mountPath: /pki/server
              name: tls-server
            - mountPath: /pki/client
              name: tls-client
      volumes:
        - name: tls-ca
          secret:
            defaultMode: 420
            optional: false
            secretName: {{ include "mlops.fullname" . }}-ca
        - name: tls-server
          secret:
            defaultMode: 420
            optional: false
            secretName: {{ include "mlops.fullname" . }}-ingestion-tls-server
        - name: tls-client
          secret:
            defaultMode: 420
            optional: false
            secretName: {{ include "mlops.fullname" . }}-ingestion-tls-client
