apiVersion: v1
data:
  BIND: :9911
  LOG_LEVEL: trace
  SERVER_REFLECTION: "true"
  SERVER_TLS: "true"
  SERVER_TLS_CA_CERT: /pki/ca/certificate
  SERVER_TLS_CERT: /pki/server/certificate
  SERVER_TLS_KEY: /pki/server/key
  STORAGE_ADDRESS: {{ include "mlops.fullname" . }}-storage:9999
  STORAGE_TLS: "true"
  STORAGE_TLS_CA_CERT: /pki/ca/certificate
  STORAGE_TLS_CERT: /pki/client/certificate
  STORAGE_TLS_KEY: /pki/client/key
kind: ConfigMap
metadata:
  name: {{ include "mlops.fullname" . }}-ingestion-env
  namespace: {{ .Release.Namespace }}
