apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops.fullname" . }}-ingestion
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 9911
      protocol: TCP
      targetPort: 9911
  selector:
    app: {{ include "mlops.fullname" . }}-ingestion
  type: {{ .Values.mlops.service_type }}
