apiVersion: v1
data:
  driverless_client_secret: {{ .Values.mlops.driverless_client_secret | b64enc | quote }}
  retrainer_client_secret: {{ .Values.mlops.retrainer_client_secret | b64enc | quote }}
  storage_client_secret: {{ .Values.mlops.storage_client_secret | b64enc | quote }}
  ui_client_secret: {{ .Values.mlops.ui_client_secret | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "mlops.fullname" . }}-oidc-client-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
