apiVersion: v1
data:
  go_pq_connection_string: {{ printf "postgres://%s:%s/%s?sslmode=%s&user=%s&password=%s" .Values.mlops.postgres_hostname .Values.mlops.postgres_port .Values.mlops.postgres_dbname .Values.mlops.postgres_sslmode .Values.mlops.postgres_username .Values.mlops.postgres_password | b64enc | quote}}
  password: {{ .Values.mlops.postgres_password | b64enc | quote }}
  username: {{ .Values.mlops.postgres_username | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "mlops.fullname" . }}-postgres-storage
  namespace: {{ .Release.Namespace }}
type: Opaque
