apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlops.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: {{ include "mlops.fullname" . }}-storage
  type: {{ .Values.mlops.service_type }}
