apiVersion: v1
data:
  COOKIE_SECURE: "false"
  DEPLOYER_ADDRESS: {{ include "mlops.fullname" . }}-deployer:9980
  DEPLOYER_CA_CERT_PATH: /pki/ca/certificate
  DEPLOYER_CERT_PATH: /pki/client/certificate
  DEPLOYER_KEY_PATH: /pki/client/key
  DEPLOYER_TLS_ENABLED: "true"
  GRAFANA_API_KEY: {{ .Values.mlops.grafana_api_key }}
  GRAFANA_URI: http://{{ include "mlops.fullname" . }}-grafana:3000
  LOG_LEVEL: debug
  MODELINGEST_ADDRESS: {{ include "mlops.fullname" . }}-ingestion:9911
  MODELINGEST_CA_CERT_PATH: /pki/ca/certificate
  MODELINGEST_CERT_PATH: /pki/client/certificate
  MODELINGEST_KEY_PATH: /pki/client/key
  MODELINGEST_TLS_ENABLED: "true"
  OIDC_CLIENT_ID: {{ .Values.mlops.ui_oidc_client_id }}
  OIDC_END_SESSION_URL: {{ printf "%s?post_logout_redirect_uri=%s://%s.%s" .Values.mlops.oidc_end_session_url .Values.mlops.protocol .Values.mlops.ui_subdomain .Values.mlops.domain | quote }}
  OIDC_PROVIDER_URL: {{ .Values.mlops.oidc_provider_url | quote }}
  OIDC_REDIRECT_URL: {{ printf "%s://%s.%s/oauth2/callback" .Values.mlops.protocol .Values.mlops.ui_subdomain .Values.mlops.domain | quote }}
  OIDC_TOKEN_INTROSPECTION_URL: {{ .Values.mlops.oidc_token_introspection_url | quote }}
  STORAGE_ADDRESS: {{ include "mlops.fullname" . }}-storage:9999
  STORAGE_CA_CERT_PATH: /pki/ca/certificate
  STORAGE_CERT_PATH: /pki/client/certificate
  STORAGE_KEY_PATH: /pki/client/key
  STORAGE_TLS_ENABLED: "true"
  TLS_ENABLED: "false"
kind: ConfigMap
metadata:
  name: {{ include "mlops.fullname" . }}-ui-env
  namespace: {{ .Release.Namespace }}
