apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 9990
      protocol: TCP
      targetPort: 9990
  selector:
    app: {{ include "mlops.fullname" . }}-ui
  type: {{ .Values.mlops.service_type }}
