apiVersion: v1
data:
  cookie_auth_secret: {{ .Values.mlops.cookie_auth_secret | b64enc | quote }}
  cookie_encrypt_secret: {{ .Values.mlops.cookie_encrypt_secret | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "mlops.fullname" . }}-ui-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
