apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: support-openshift-rwtsm
  name: support-openshift-rwtsm-mlopshelm-us-east-2a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: support-openshift-rwtsm
      machine.openshift.io/cluster-api-machineset: support-openshift-rwtsm-mlopshelm-us-east-2a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: support-openshift-rwtsm
        machine.openshift.io/cluster-api-machine-role: mlopshelm
        machine.openshift.io/cluster-api-machine-type: mlopshelm
        machine.openshift.io/cluster-api-machineset: support-openshift-rwtsm-mlopshelm-us-east-2a
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/mlopshelm: "mlopshelm"
      providerSpec:
        value:
          ami:
            id: ami-0c84b5c5255ec4777
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: support-openshift-rwtsm-worker-profile
          instanceType: m5.xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-2a
            region: us-east-2
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - support-openshift-rwtsm-worker-sg
          subnet:
            filters:
              - name: tag:Name
                values:
                  - support-openshift-rwtsm-private-us-east-2a
          tags:
            - name: kubernetes.io/cluster/support-openshift-rwtsm
              value: owned
          userDataSecret:
            name: worker-user-data
